# Site settings
## Change the values as needed.
title: Guru's Blog
email: guruprasadah08@gmail.com
description: "A place where I may or may not rant about stuff"
keywords: "jekyll, xda, android, arduino, stuff"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://guruprasadah.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  #facebook: brijeshb42
  #twitter: brijeshb42
  email: guruprasadah08@gmail.com
  github: guruprasadah/
exclude:
  - bower_components
  - README.md
full_name: Guruprasad AH

##set this to enable disqus commenting
disqus: Guruprasad

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
